
POST   http://localhost:4300/api/signup  HTTP/1.1
Content-Type: application/json 

{
    "firstName":"rajes",
    "lastName":"sharma",
    "username":"rsm",
    "email":"rajesh@gmail.com",
    "password":"rsm345",
    "role":"admin",
    "contactNumber":"9586110306",
    "profilePicture":"not"
}


######### signin
POST      http://localhost:4300/api/signin  HTTP/1.1
Content-Type: application/json 

{
    "email":"rajesh@gmail.com",
    "password":"rsm345"
}

######### products

GET  http://localhost:4300/api/products HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFkMmZmMTRlYzgyYzFjM2I0NThkN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc0NzI1MiwiZXhwIjoxNzA1ODMzNjUyfQ.vuKwLQfnuwVeMdRH7urQZl769NMenyW1gFX_oqp3Ug4


######### addNewProducts

POST   http://localhost:4300/api/products HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFkMmZmMTRlYzgyYzFjM2I0NThkN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc0NzI1MiwiZXhwIjoxNzA1ODMzNjUyfQ.vuKwLQfnuwVeMdRH7urQZl769NMenyW1gFX_oqp3Ug4

{
    "name":"cherry",
    "price":45
}






######### addNew contact

POST   http://localhost:4300/api/contact HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFiYzM3NjBiZjg1MWMwYWFiYmM2ZGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc1NTUzNCwiZXhwIjoxNzA1ODQxOTM0fQ.qmV05EZG9pQkoP7lcy-mQ9-FwVcRPPT3YRaVgCJo6_4

{
    "name":"rjsml",
    "phone":"7786210503"
}








######### contacts

GET  http://localhost:4300/api/contact HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFiYzM3NjBiZjg1MWMwYWFiYmM2ZGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc1NTUzNCwiZXhwIjoxNzA1ODQxOTM0fQ.qmV05EZG9pQkoP7lcy-mQ9-FwVcRPPT3YRaVgCJo6_4





######### signout
POST      http://localhost:4300/api/signout  HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFkMmZmMTRlYzgyYzFjM2I0NThkN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc1MTIyOSwiZXhwIjoxNzA1ODM3NjI5fQ.qhbG-jZxdNDcfDmebrV93D9Qfpzf6m3Je4Vp7iwg5I4




######### selectedProducts add

POST    http://localhost:4300/api/selected/65abbaf3abc395a6892a9f08 HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFkMmZmMTRlYzgyYzFjM2I0NThkN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc1MTIyOSwiZXhwIjoxNzA1ODM3NjI5fQ.qhbG-jZxdNDcfDmebrV93D9Qfpzf6m3Je4Vp7iwg5I4

{
    "name":"cherry",
    "price":45
}


######### selectedProducts get

GET     http://localhost:4300/api/selected HTTP/1.1
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFiYzM3NjBiZjg1MWMwYWFiYmM2ZGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTc1NTUzNCwiZXhwIjoxNzA1ODQxOTM0fQ.qmV05EZG9pQkoP7lcy-mQ9-FwVcRPPT3YRaVgCJo6_4
